const headcanon = (name) => {
  var name = name || "This character";
  const randomElement = (arr) => arr[Math.floor(Math.random() * arr.length)];
  const item = [
    'a sword',
    'a knife',
    'a stuffed animal',
    'a maid dress',
    'an extensive manga collection',
    'a deck of yugioh cards',
    'half of a watermelon',
  ]
  const song = [
    'Let It Go',
    'Never Gonna Give You Up',
    'All Star',
    'the Ouran Highschool Host Club theme song',
    'every Britney Spears song',
    'every Hatsune Miku song',
  ]
  const sexuality = [
    'gay',
    'bisexual',
    'asexual',
    'queer',
    'aromantic',
    'aro ace',
    'pansexual',
    'trans',
  ]
  const fear = [
    'spiders',
    'heights',
    'water',
    'dolls',
    'people',
    'doctors',
    'water',
  ]
  const pet = [
    'dog',
    'cat',
    'bird',
    'hamster',
    'snake',
    'squirrel',
    'lizard',
  ]
  const subject = [
    'Math',
    'English',
    'Science',
    'Social Studies',
    'Gym',
  ]
  const data = [
    `${name} always has ${randomElement(item)} on them.`,
    `${name} is in your house.`,
    `${name} shops exclusively at ${randomElement(["Hot Topic", "Claires", "thrift stores"])}.`,
    `${name} does not know how to read.`,
    `${name} knows the lyrics to ${randomElement(song)} by heart.`,
    `${name} was dropped out of a window as a child.`,
    `${name} is very good at walking in platform heels.`,
    `${name} is ${randomElement(sexuality)}.`,
    `${name} is tumblr famous.`,
    `${name} is oblivious to any and all romantic interest someone may show them.`,
    `${name} has an embarrassing old deviant art account.`,
    `${name} has ${randomElement(item)} under their bed.`,
    `${name} has an incredible spice tolerance.`,
    `${name} has an intense fear of ${randomElement(fear)}.`,
    `${name} had an emo phase.`,
    `${name} is very good at using chopsticks.`,
    `${name} likes to eat straight coffee beans.`,
    `${name} is awful with technology and doesn't know how to use a smartphone.`,
    `${name} killed Princess Diana.`,
    `${name} can't sit in a chair properly.`,
    `${name} set a public school on fire and got away with it.`,
    `${name} could easily survive The Hunger Games.`,
    `${name} has not showered in two and a half weeks.`,
    `${name} forgets to eat sometimes.`,
    `${name} would succumb to the fog.`,
    `${name} is a great artist.`,
    `${name} does not know what sleep is.`,
    `${name} enjoys doing taxes.`,
    `If someone they knew committed a crime, ${name} would cover for them.`,
    `${name} reads ${randomElement(["ao3", "wattpad"])}.`,
    `${name} got hit by a bus once.`,
    `${name} likes board games, but no one else wants to play with them.`,
    `${name} is a crybaby.`,
    `${name} listens to 80s music.`,
    `It would not take much for ${name} to turn evil.`,
    `${name} will go feral. Watch out.`,
    `${name} has a pet ${randomElement(pet)}.`,
    `${name} would buy clothes from the soup store.`,
    `${name} is ${randomElement(['a youngest','a middle','an oldest'])} child.`,
    `${name} can play the ${randomElement(['piano','guitar','kazoo'])}.`,
    `${name} knows fnaf lore.`,
    `${name} is an ${randomElement(["introvert", "extrovert"])}.`,
    `${name} ${randomElement(["can", "cannot"])} drive.`,
    `${name} is not good with social cues.`,
    `${name} is not allowed to drink energy drinks.`,
    `${name} tackles and wrestles people to show affection.`,
    `${name} is afraid of doing anything without their parent's permission.`,
    `${name} is a horrible liar.`,
    `${name} will remind others in the midst of chaos how good **they're** being.`,
    `${name} has fallen asleep at their desk while working in the middle of the night.`,
    `${name} tells dad jokes.`,
    `${name}'s favorite color is pink.`,
    `${name} doesn't own a single pair of matching socks.`,
    `${name} has an incredible long-term memory but an awful short-term memory.`,
    `${name} has an incredible short-term memory but an awful long-term memory.`,
    `${name} bites their nails.`,
    `${name} is ${randomElement(['awful','great'])} with kids.`,
    `${name} desperately needs a hug but doesn't know it and refuses to ask for one.`,
    `If ${name} likes someone, they will give them a pretty rock.`,
    `${name} is very willing to eat inedible things.`,
    `${name} steals other people's clothes.`,
    `${name} can ${randomElement(['kill you in an instant','beat you up','hug you'])} ${randomElement(['if deserved','and will',"but won't"])}.`,
    `${name} makes your mom jokes.`,
    `${name}'s ${randomElement(['favorite','least favorite'])} subject in school was ${randomElement(subject)}.`,
    `${name} stole a lollipop at the checkout when they were 5 and they still feel guilty about it.`,
    `If ${name} was presented with an intergalactic portal, they would enter it without question.`,
    `${name} knocks people over by hugging them.`,
    `${name} cringes at their middle school yearbook photos.`,
    `${name} instinctively cleans messes in their own house as well as other people's.`,
    `${name} sings in the shower.`,
    `${name} nearly drowned in a river as a child.`,
    `${name} sleeps in until noon.`,
    `${name} speaks only in meme references.`,
    `${name} has a diary that they write in with a glittery gel pen.`,
    `${name} is a ${randomElement(['cat','dog'])} person.`,
    `If the source media was a musical, ${name} would be the one character that asks why everyone is singing.`,
    `${name} is smart but also very stupid.`,
    `${name} is the gay cousin.`,
    `${name} uses the word '${randomElement(['dude','like','fuck'])}' like a comma.`,
    `${name} believes in ghosts and insists on trying to summon one at every sleepover.`,
    `${name} wears Hello Kitty socks.`,
    `${name} ${randomElement(['likes','hates'])} being alone.`,
    `${name} chews their nails when nervous.`,
    `${name} almost drank the lethal dosage of caffeine once.`,
    `${name} gets road rage.`,
    `${name} has a mary sue oc.`,
    `${name} sucks at saying tongue twisters.`,
    `${name} needs a nightlight to sleep.`,
    `${name} cries while watching Disney movies.`,
    `${name} has a Roblox account.`,
    `${name} is a ${randomElement(['top','bottom','switch'])}.`,
    `${name} is constantly singing for no reason.`,
    `${name} is a simp.`,
    `${name} can't spell restaurant.`,
    `${name} has chronic nightmares.`,
    `${name} has been to prison.`,
    `${name} watched the Sonic movie.`,
    `${name} voted ${randomElement(['sans','Reigen'])} in the Tumblr sexyman poll.`,
    `${name} has punched a hole in their wall.`,
    `${name} does intricate and expensive cosplays.`,
    `${name} is a sleepwalker.`,
    `${name} is a theater kid.`,
    `${name} wakes up on November 1st and starts decorating for Christmas.`,
    `${name} is afraid to close their eyes in the shower.`,
    `${name} gets into Twitter discourse.`,
    `${name} has been canceled on Twitter.`,
    `${name} has a very low alcohol tolerance.`,
    `${name} fucked your mom.`,
    `${name} uses two-in-one shampoo and conditioner.`,
    `${name} bullies kids on Roblox.`,
    `${name} role plays on Discord.`,
    `${name} can't make the voices go away.`,
    `${name} screams like an anime girl.`,
    `${name} is going to ${randomElement(['heaven','hell'])}.`,
    `${name} watches My Little Pony.`,
    `${name} was forced to eat cement as a child.`,
    `${name} hacks their stats in every video game they play.`,
    `${name} believes in Santa.`,
    `${name} doesn't know how to say '${randomElement(['no',"they're sorry"])}'.`,
    `${name} crashed a riding lawn mower into their fence.`,
    `${name} is a very good singer.`,
    `${name} cracks their knuckles very loudly.`,
    `${name} is unemployed.`,
    `${name} can't handle criticism.`,
    `${name} gets bullied on Roblox.`,
    `${name} is a sigma.`
  ];
  return randomElement(data);
};
module.exports = headcanon;
